version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt
      - run:
          name: Run tests
          command: python3 test.py

workflows:
  sample:
    jobs:
      - build-and-test
